// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REQUEST_TEST_H_
#define FLATBUFFERS_GENERATED_REQUEST_TEST_H_

#include "flatbuffers/flatbuffers.h"

#include "shared_generated.h"

namespace test {

struct request;
struct requestBuilder;

struct request FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef requestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_ID = 4,
    VT_STATUS = 6,
    VT_MESSAGE = 8,
    VT_NAMES = 10
  };
  uint64_t req_id() const {
    return GetField<uint64_t>(VT_REQ_ID, 0);
  }
  test::Status status() const {
    return static_cast<test::Status>(GetField<int16_t>(VT_STATUS, 0));
  }
  const flatbuffers::String *message() const {
    return GetPointer<const flatbuffers::String *>(VT_MESSAGE);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *names() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>> *>(VT_NAMES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_REQ_ID) &&
           VerifyField<int16_t>(verifier, VT_STATUS) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           verifier.VerifyString(message()) &&
           VerifyOffset(verifier, VT_NAMES) &&
           verifier.VerifyVector(names()) &&
           verifier.VerifyVectorOfStrings(names()) &&
           verifier.EndTable();
  }
};

struct requestBuilder {
  typedef request Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_req_id(uint64_t req_id) {
    fbb_.AddElement<uint64_t>(request::VT_REQ_ID, req_id, 0);
  }
  void add_status(test::Status status) {
    fbb_.AddElement<int16_t>(request::VT_STATUS, static_cast<int16_t>(status), 0);
  }
  void add_message(flatbuffers::Offset<flatbuffers::String> message) {
    fbb_.AddOffset(request::VT_MESSAGE, message);
  }
  void add_names(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names) {
    fbb_.AddOffset(request::VT_NAMES, names);
  }
  explicit requestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<request> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<request>(end);
    return o;
  }
};

inline flatbuffers::Offset<request> Createrequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t req_id = 0,
    test::Status status = test::Status_Success,
    flatbuffers::Offset<flatbuffers::String> message = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>> names = 0) {
  requestBuilder builder_(_fbb);
  builder_.add_req_id(req_id);
  builder_.add_names(names);
  builder_.add_message(message);
  builder_.add_status(status);
  return builder_.Finish();
}

inline flatbuffers::Offset<request> CreaterequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t req_id = 0,
    test::Status status = test::Status_Success,
    const char *message = nullptr,
    const std::vector<flatbuffers::Offset<flatbuffers::String>> *names = nullptr) {
  auto message__ = message ? _fbb.CreateString(message) : 0;
  auto names__ = names ? _fbb.CreateVector<flatbuffers::Offset<flatbuffers::String>>(*names) : 0;
  return test::Createrequest(
      _fbb,
      req_id,
      status,
      message__,
      names__);
}

inline const test::request *Getrequest(const void *buf) {
  return flatbuffers::GetRoot<test::request>(buf);
}

inline const test::request *GetSizePrefixedrequest(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<test::request>(buf);
}

inline const char *requestIdentifier() {
  return "requ";
}

inline bool requestBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, requestIdentifier());
}

inline bool VerifyrequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<test::request>(requestIdentifier());
}

inline bool VerifySizePrefixedrequestBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<test::request>(requestIdentifier());
}

inline void FinishrequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<test::request> root) {
  fbb.Finish(root, requestIdentifier());
}

inline void FinishSizePrefixedrequestBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<test::request> root) {
  fbb.FinishSizePrefixed(root, requestIdentifier());
}

}  // namespace test

#endif  // FLATBUFFERS_GENERATED_REQUEST_TEST_H_
