// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SHARED_TEST_H_
#define FLATBUFFERS_GENERATED_SHARED_TEST_H_

#include "flatbuffers/flatbuffers.h"

namespace test {

enum Status {
  Status_Success = 0,
  Status_Failed = 1,
  Status_InternalError = 2,
  Status_MIN = Status_Success,
  Status_MAX = Status_InternalError
};

inline const Status (&EnumValuesStatus())[3] {
  static const Status values[] = {
    Status_Success,
    Status_Failed,
    Status_InternalError
  };
  return values;
}

inline const char * const *EnumNamesStatus() {
  static const char * const names[4] = {
    "Success",
    "Failed",
    "InternalError",
    nullptr
  };
  return names;
}

inline const char *EnumNameStatus(Status e) {
  if (flatbuffers::IsOutRange(e, Status_Success, Status_InternalError)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesStatus()[index];
}

}  // namespace test

#endif  // FLATBUFFERS_GENERATED_SHARED_TEST_H_
