// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMAND_FLAT_H_
#define FLATBUFFERS_GENERATED_COMMAND_FLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace flat {

struct Command;
struct CommandBuilder;

struct Command FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_ROOM_ID = 6,
    VT_MOVE_X = 8,
    VT_MOVE_Y = 10,
    VT_ATTACK = 12,
    VT_SKILL1 = 14,
    VT_SKILL2 = 16
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint32_t room_id() const {
    return GetField<uint32_t>(VT_ROOM_ID, 0);
  }
  int8_t move_x() const {
    return GetField<int8_t>(VT_MOVE_X, 0);
  }
  int8_t move_y() const {
    return GetField<int8_t>(VT_MOVE_Y, 0);
  }
  bool attack() const {
    return GetField<uint8_t>(VT_ATTACK, 0) != 0;
  }
  bool skill1() const {
    return GetField<uint8_t>(VT_SKILL1, 0) != 0;
  }
  bool skill2() const {
    return GetField<uint8_t>(VT_SKILL2, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID) &&
           VerifyField<uint32_t>(verifier, VT_ROOM_ID) &&
           VerifyField<int8_t>(verifier, VT_MOVE_X) &&
           VerifyField<int8_t>(verifier, VT_MOVE_Y) &&
           VerifyField<uint8_t>(verifier, VT_ATTACK) &&
           VerifyField<uint8_t>(verifier, VT_SKILL1) &&
           VerifyField<uint8_t>(verifier, VT_SKILL2) &&
           verifier.EndTable();
  }
};

struct CommandBuilder {
  typedef Command Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(Command::VT_PLAYER_ID, player_id, 0);
  }
  void add_room_id(uint32_t room_id) {
    fbb_.AddElement<uint32_t>(Command::VT_ROOM_ID, room_id, 0);
  }
  void add_move_x(int8_t move_x) {
    fbb_.AddElement<int8_t>(Command::VT_MOVE_X, move_x, 0);
  }
  void add_move_y(int8_t move_y) {
    fbb_.AddElement<int8_t>(Command::VT_MOVE_Y, move_y, 0);
  }
  void add_attack(bool attack) {
    fbb_.AddElement<uint8_t>(Command::VT_ATTACK, static_cast<uint8_t>(attack), 0);
  }
  void add_skill1(bool skill1) {
    fbb_.AddElement<uint8_t>(Command::VT_SKILL1, static_cast<uint8_t>(skill1), 0);
  }
  void add_skill2(bool skill2) {
    fbb_.AddElement<uint8_t>(Command::VT_SKILL2, static_cast<uint8_t>(skill2), 0);
  }
  explicit CommandBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Command> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Command>(end);
    return o;
  }
};

inline flatbuffers::Offset<Command> CreateCommand(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint32_t room_id = 0,
    int8_t move_x = 0,
    int8_t move_y = 0,
    bool attack = false,
    bool skill1 = false,
    bool skill2 = false) {
  CommandBuilder builder_(_fbb);
  builder_.add_room_id(room_id);
  builder_.add_player_id(player_id);
  builder_.add_skill2(skill2);
  builder_.add_skill1(skill1);
  builder_.add_attack(attack);
  builder_.add_move_y(move_y);
  builder_.add_move_x(move_x);
  return builder_.Finish();
}

inline const flat::Command *GetCommand(const void *buf) {
  return flatbuffers::GetRoot<flat::Command>(buf);
}

inline const flat::Command *GetSizePrefixedCommand(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::Command>(buf);
}

inline const char *CommandIdentifier() {
  return "comm";
}

inline bool CommandBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, CommandIdentifier());
}

inline bool VerifyCommandBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::Command>(CommandIdentifier());
}

inline bool VerifySizePrefixedCommandBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::Command>(CommandIdentifier());
}

inline void FinishCommandBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Command> root) {
  fbb.Finish(root, CommandIdentifier());
}

inline void FinishSizePrefixedCommandBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Command> root) {
  fbb.FinishSizePrefixed(root, CommandIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_COMMAND_FLAT_H_
