// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENTITY_FLAT_H_
#define FLATBUFFERS_GENERATED_ENTITY_FLAT_H_

#include "flatbuffers/flatbuffers.h"

namespace flat {

struct Entity;
struct EntityBuilder;

struct Entity FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_HP = 6,
    VT_STATUS_FLAGS = 8,
    VT_X = 10,
    VT_Y = 12,
    VT_VX = 14,
    VT_VY = 16,
    VT_ATTACK_COOLDOWN = 18,
    VT_SKILL1_COOLDOWN = 20,
    VT_SKILL2_COLLDOWN = 22
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  uint32_t status_flags() const {
    return GetField<uint32_t>(VT_STATUS_FLAGS, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float vx() const {
    return GetField<float>(VT_VX, 0.0f);
  }
  float vy() const {
    return GetField<float>(VT_VY, 0.0f);
  }
  float attack_cooldown() const {
    return GetField<float>(VT_ATTACK_COOLDOWN, 0.0f);
  }
  float skill1_cooldown() const {
    return GetField<float>(VT_SKILL1_COOLDOWN, 0.0f);
  }
  float skill2_colldown() const {
    return GetField<float>(VT_SKILL2_COLLDOWN, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID) &&
           VerifyField<int32_t>(verifier, VT_HP) &&
           VerifyField<uint32_t>(verifier, VT_STATUS_FLAGS) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           VerifyField<float>(verifier, VT_VX) &&
           VerifyField<float>(verifier, VT_VY) &&
           VerifyField<float>(verifier, VT_ATTACK_COOLDOWN) &&
           VerifyField<float>(verifier, VT_SKILL1_COOLDOWN) &&
           VerifyField<float>(verifier, VT_SKILL2_COLLDOWN) &&
           verifier.EndTable();
  }
};

struct EntityBuilder {
  typedef Entity Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(Entity::VT_ENTITY_ID, entity_id, 0);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(Entity::VT_HP, hp, 0);
  }
  void add_status_flags(uint32_t status_flags) {
    fbb_.AddElement<uint32_t>(Entity::VT_STATUS_FLAGS, status_flags, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(Entity::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Entity::VT_Y, y, 0.0f);
  }
  void add_vx(float vx) {
    fbb_.AddElement<float>(Entity::VT_VX, vx, 0.0f);
  }
  void add_vy(float vy) {
    fbb_.AddElement<float>(Entity::VT_VY, vy, 0.0f);
  }
  void add_attack_cooldown(float attack_cooldown) {
    fbb_.AddElement<float>(Entity::VT_ATTACK_COOLDOWN, attack_cooldown, 0.0f);
  }
  void add_skill1_cooldown(float skill1_cooldown) {
    fbb_.AddElement<float>(Entity::VT_SKILL1_COOLDOWN, skill1_cooldown, 0.0f);
  }
  void add_skill2_colldown(float skill2_colldown) {
    fbb_.AddElement<float>(Entity::VT_SKILL2_COLLDOWN, skill2_colldown, 0.0f);
  }
  explicit EntityBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Entity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Entity>(end);
    return o;
  }
};

inline flatbuffers::Offset<Entity> CreateEntity(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    int32_t hp = 0,
    uint32_t status_flags = 0,
    float x = 0.0f,
    float y = 0.0f,
    float vx = 0.0f,
    float vy = 0.0f,
    float attack_cooldown = 0.0f,
    float skill1_cooldown = 0.0f,
    float skill2_colldown = 0.0f) {
  EntityBuilder builder_(_fbb);
  builder_.add_skill2_colldown(skill2_colldown);
  builder_.add_skill1_cooldown(skill1_cooldown);
  builder_.add_attack_cooldown(attack_cooldown);
  builder_.add_vy(vy);
  builder_.add_vx(vx);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_status_flags(status_flags);
  builder_.add_hp(hp);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

inline const flat::Entity *GetEntity(const void *buf) {
  return flatbuffers::GetRoot<flat::Entity>(buf);
}

inline const flat::Entity *GetSizePrefixedEntity(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::Entity>(buf);
}

inline const char *EntityIdentifier() {
  return "enti";
}

inline bool EntityBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, EntityIdentifier());
}

inline bool VerifyEntityBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::Entity>(EntityIdentifier());
}

inline bool VerifySizePrefixedEntityBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::Entity>(EntityIdentifier());
}

inline void FinishEntityBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Entity> root) {
  fbb.Finish(root, EntityIdentifier());
}

inline void FinishSizePrefixedEntityBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Entity> root) {
  fbb.FinishSizePrefixed(root, EntityIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_ENTITY_FLAT_H_
