// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FRAME_FLAT_H_
#define FLATBUFFERS_GENERATED_FRAME_FLAT_H_

#include "flatbuffers/flatbuffers.h"

#include "command_fb.h"
#include "entity_fb.h"

namespace flat {

struct Frame;
struct FrameBuilder;

enum DataType {
  DataType_None = 0,
  DataType_Entitys = 1,
  DataType_Commands = 2,
  DataType_MIN = DataType_None,
  DataType_MAX = DataType_Commands
};

inline const DataType (&EnumValuesDataType())[3] {
  static const DataType values[] = {
    DataType_None,
    DataType_Entitys,
    DataType_Commands
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[4] = {
    "None",
    "Entitys",
    "Commands",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (flatbuffers::IsOutRange(e, DataType_None, DataType_Commands)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

struct Frame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_TYPE = 6,
    VT_ENTITIES = 8,
    VT_COMMANDS = 10
  };
  uint32_t tick() const {
    return GetField<uint32_t>(VT_TICK, 0);
  }
  flat::DataType type() const {
    return static_cast<flat::DataType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::Entity>> *entities() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::Entity>> *>(VT_ENTITIES);
  }
  const flatbuffers::Vector<flatbuffers::Offset<flat::Command>> *commands() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flat::Command>> *>(VT_COMMANDS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TICK) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyVector(commands()) &&
           verifier.VerifyVectorOfTables(commands()) &&
           verifier.EndTable();
  }
};

struct FrameBuilder {
  typedef Frame Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_tick(uint32_t tick) {
    fbb_.AddElement<uint32_t>(Frame::VT_TICK, tick, 0);
  }
  void add_type(flat::DataType type) {
    fbb_.AddElement<int8_t>(Frame::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_entities(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::Entity>>> entities) {
    fbb_.AddOffset(Frame::VT_ENTITIES, entities);
  }
  void add_commands(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::Command>>> commands) {
    fbb_.AddOffset(Frame::VT_COMMANDS, commands);
  }
  explicit FrameBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Frame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Frame>(end);
    return o;
  }
};

inline flatbuffers::Offset<Frame> CreateFrame(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    flat::DataType type = flat::DataType_None,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::Entity>>> entities = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<flat::Command>>> commands = 0) {
  FrameBuilder builder_(_fbb);
  builder_.add_commands(commands);
  builder_.add_entities(entities);
  builder_.add_tick(tick);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Frame> CreateFrameDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    flat::DataType type = flat::DataType_None,
    const std::vector<flatbuffers::Offset<flat::Entity>> *entities = nullptr,
    const std::vector<flatbuffers::Offset<flat::Command>> *commands = nullptr) {
  auto entities__ = entities ? _fbb.CreateVector<flatbuffers::Offset<flat::Entity>>(*entities) : 0;
  auto commands__ = commands ? _fbb.CreateVector<flatbuffers::Offset<flat::Command>>(*commands) : 0;
  return flat::CreateFrame(
      _fbb,
      tick,
      type,
      entities__,
      commands__);
}

inline const flat::Frame *GetFrame(const void *buf) {
  return flatbuffers::GetRoot<flat::Frame>(buf);
}

inline const flat::Frame *GetSizePrefixedFrame(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<flat::Frame>(buf);
}

inline const char *FrameIdentifier() {
  return "fram";
}

inline bool FrameBufferHasIdentifier(const void *buf) {
  return flatbuffers::BufferHasIdentifier(
      buf, FrameIdentifier());
}

inline bool VerifyFrameBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<flat::Frame>(FrameIdentifier());
}

inline bool VerifySizePrefixedFrameBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<flat::Frame>(FrameIdentifier());
}

inline void FinishFrameBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Frame> root) {
  fbb.Finish(root, FrameIdentifier());
}

inline void FinishSizePrefixedFrameBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<flat::Frame> root) {
  fbb.FinishSizePrefixed(root, FrameIdentifier());
}

}  // namespace flat

#endif  // FLATBUFFERS_GENERATED_FRAME_FLAT_H_
