// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_IO_IO_H_
#define FLATBUFFERS_GENERATED_IO_IO_H_

#include "flatbuffers/flatbuffers.h"

namespace io {

struct Command;
struct CommandBuilder;

struct Entity;
struct EntityBuilder;

struct Frame;
struct FrameBuilder;

enum DataType {
  DataType_None = 0,
  DataType_Entitys = 1,
  DataType_Commands = 2,
  DataType_MIN = DataType_None,
  DataType_MAX = DataType_Commands
};

inline const DataType (&EnumValuesDataType())[3] {
  static const DataType values[] = {
    DataType_None,
    DataType_Entitys,
    DataType_Commands
  };
  return values;
}

inline const char * const *EnumNamesDataType() {
  static const char * const names[4] = {
    "None",
    "Entitys",
    "Commands",
    nullptr
  };
  return names;
}

inline const char *EnumNameDataType(DataType e) {
  if (flatbuffers::IsOutRange(e, DataType_None, DataType_Commands)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDataType()[index];
}

struct Command FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CommandBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYER_ID = 4,
    VT_TICK = 6,
    VT_MOVE_X = 8,
    VT_MOVE_Y = 10,
    VT_ATTACK = 12,
    VT_SKILL1 = 14,
    VT_SKILL2 = 16
  };
  uint32_t player_id() const {
    return GetField<uint32_t>(VT_PLAYER_ID, 0);
  }
  uint32_t tick() const {
    return GetField<uint32_t>(VT_TICK, 0);
  }
  int8_t move_x() const {
    return GetField<int8_t>(VT_MOVE_X, 0);
  }
  int8_t move_y() const {
    return GetField<int8_t>(VT_MOVE_Y, 0);
  }
  bool attack() const {
    return GetField<uint8_t>(VT_ATTACK, 0) != 0;
  }
  bool skill1() const {
    return GetField<uint8_t>(VT_SKILL1, 0) != 0;
  }
  bool skill2() const {
    return GetField<uint8_t>(VT_SKILL2, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ID) &&
           VerifyField<uint32_t>(verifier, VT_TICK) &&
           VerifyField<int8_t>(verifier, VT_MOVE_X) &&
           VerifyField<int8_t>(verifier, VT_MOVE_Y) &&
           VerifyField<uint8_t>(verifier, VT_ATTACK) &&
           VerifyField<uint8_t>(verifier, VT_SKILL1) &&
           VerifyField<uint8_t>(verifier, VT_SKILL2) &&
           verifier.EndTable();
  }
};

struct CommandBuilder {
  typedef Command Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_player_id(uint32_t player_id) {
    fbb_.AddElement<uint32_t>(Command::VT_PLAYER_ID, player_id, 0);
  }
  void add_tick(uint32_t tick) {
    fbb_.AddElement<uint32_t>(Command::VT_TICK, tick, 0);
  }
  void add_move_x(int8_t move_x) {
    fbb_.AddElement<int8_t>(Command::VT_MOVE_X, move_x, 0);
  }
  void add_move_y(int8_t move_y) {
    fbb_.AddElement<int8_t>(Command::VT_MOVE_Y, move_y, 0);
  }
  void add_attack(bool attack) {
    fbb_.AddElement<uint8_t>(Command::VT_ATTACK, static_cast<uint8_t>(attack), 0);
  }
  void add_skill1(bool skill1) {
    fbb_.AddElement<uint8_t>(Command::VT_SKILL1, static_cast<uint8_t>(skill1), 0);
  }
  void add_skill2(bool skill2) {
    fbb_.AddElement<uint8_t>(Command::VT_SKILL2, static_cast<uint8_t>(skill2), 0);
  }
  explicit CommandBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Command> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Command>(end);
    return o;
  }
};

inline flatbuffers::Offset<Command> CreateCommand(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t player_id = 0,
    uint32_t tick = 0,
    int8_t move_x = 0,
    int8_t move_y = 0,
    bool attack = false,
    bool skill1 = false,
    bool skill2 = false) {
  CommandBuilder builder_(_fbb);
  builder_.add_tick(tick);
  builder_.add_player_id(player_id);
  builder_.add_skill2(skill2);
  builder_.add_skill1(skill1);
  builder_.add_attack(attack);
  builder_.add_move_y(move_y);
  builder_.add_move_x(move_x);
  return builder_.Finish();
}

struct Entity FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef EntityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_HP = 6,
    VT_STATUS_FLAGS = 8,
    VT_X = 10,
    VT_Y = 12,
    VT_VX = 14,
    VT_VY = 16
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  uint32_t status_flags() const {
    return GetField<uint32_t>(VT_STATUS_FLAGS, 0);
  }
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float vx() const {
    return GetField<float>(VT_VX, 0.0f);
  }
  float vy() const {
    return GetField<float>(VT_VY, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID) &&
           VerifyField<int32_t>(verifier, VT_HP) &&
           VerifyField<uint32_t>(verifier, VT_STATUS_FLAGS) &&
           VerifyField<float>(verifier, VT_X) &&
           VerifyField<float>(verifier, VT_Y) &&
           VerifyField<float>(verifier, VT_VX) &&
           VerifyField<float>(verifier, VT_VY) &&
           verifier.EndTable();
  }
};

struct EntityBuilder {
  typedef Entity Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(Entity::VT_ENTITY_ID, entity_id, 0);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(Entity::VT_HP, hp, 0);
  }
  void add_status_flags(uint32_t status_flags) {
    fbb_.AddElement<uint32_t>(Entity::VT_STATUS_FLAGS, status_flags, 0);
  }
  void add_x(float x) {
    fbb_.AddElement<float>(Entity::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Entity::VT_Y, y, 0.0f);
  }
  void add_vx(float vx) {
    fbb_.AddElement<float>(Entity::VT_VX, vx, 0.0f);
  }
  void add_vy(float vy) {
    fbb_.AddElement<float>(Entity::VT_VY, vy, 0.0f);
  }
  explicit EntityBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Entity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Entity>(end);
    return o;
  }
};

inline flatbuffers::Offset<Entity> CreateEntity(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    int32_t hp = 0,
    uint32_t status_flags = 0,
    float x = 0.0f,
    float y = 0.0f,
    float vx = 0.0f,
    float vy = 0.0f) {
  EntityBuilder builder_(_fbb);
  builder_.add_vy(vy);
  builder_.add_vx(vx);
  builder_.add_y(y);
  builder_.add_x(x);
  builder_.add_status_flags(status_flags);
  builder_.add_hp(hp);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

struct Frame FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_TYPE = 6,
    VT_ENTITIES = 8,
    VT_COMMANDS = 10
  };
  uint32_t tick() const {
    return GetField<uint32_t>(VT_TICK, 0);
  }
  io::DataType type() const {
    return static_cast<io::DataType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const flatbuffers::Vector<flatbuffers::Offset<io::Entity>> *entities() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<io::Entity>> *>(VT_ENTITIES);
  }
  const flatbuffers::Vector<flatbuffers::Offset<io::Command>> *commands() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<io::Command>> *>(VT_COMMANDS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_TICK) &&
           VerifyField<int8_t>(verifier, VT_TYPE) &&
           VerifyOffset(verifier, VT_ENTITIES) &&
           verifier.VerifyVector(entities()) &&
           verifier.VerifyVectorOfTables(entities()) &&
           VerifyOffset(verifier, VT_COMMANDS) &&
           verifier.VerifyVector(commands()) &&
           verifier.VerifyVectorOfTables(commands()) &&
           verifier.EndTable();
  }
};

struct FrameBuilder {
  typedef Frame Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_tick(uint32_t tick) {
    fbb_.AddElement<uint32_t>(Frame::VT_TICK, tick, 0);
  }
  void add_type(io::DataType type) {
    fbb_.AddElement<int8_t>(Frame::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_entities(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<io::Entity>>> entities) {
    fbb_.AddOffset(Frame::VT_ENTITIES, entities);
  }
  void add_commands(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<io::Command>>> commands) {
    fbb_.AddOffset(Frame::VT_COMMANDS, commands);
  }
  explicit FrameBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Frame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Frame>(end);
    return o;
  }
};

inline flatbuffers::Offset<Frame> CreateFrame(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    io::DataType type = io::DataType_None,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<io::Entity>>> entities = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<io::Command>>> commands = 0) {
  FrameBuilder builder_(_fbb);
  builder_.add_commands(commands);
  builder_.add_entities(entities);
  builder_.add_tick(tick);
  builder_.add_type(type);
  return builder_.Finish();
}

inline flatbuffers::Offset<Frame> CreateFrameDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t tick = 0,
    io::DataType type = io::DataType_None,
    const std::vector<flatbuffers::Offset<io::Entity>> *entities = nullptr,
    const std::vector<flatbuffers::Offset<io::Command>> *commands = nullptr) {
  auto entities__ = entities ? _fbb.CreateVector<flatbuffers::Offset<io::Entity>>(*entities) : 0;
  auto commands__ = commands ? _fbb.CreateVector<flatbuffers::Offset<io::Command>>(*commands) : 0;
  return io::CreateFrame(
      _fbb,
      tick,
      type,
      entities__,
      commands__);
}

}  // namespace io

#endif  // FLATBUFFERS_GENERATED_IO_IO_H_
